# This example is to show how to automatically stop the default web server when launching Docker containers.
#
# By default a web server will be started using script /var/www/server.php when a Docker container is booted. During
# local development you might not want to have the web server running. In this case, please have environment variable
# DISABLE_DEFAULT_SERVER set to "true" or 1.
version: '3'

services:
  app:
    image: phpswoole/swoole
    environment:
      DISABLE_DEFAULT_SERVER: 1
    ports:
      - 80:9501
