# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.4.16.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.1.33"
  - "7.2.27"
  - "7.3.14"
  - "7.4.2"
image:
  composer:
    version: "1.9.3"
