# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.7.1.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2.34"
  - "7.3.29"
  - "7.4.22"
  - "8.0.9"
image:
  composer:
    version: "2.1.6"
