# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:6.1.1.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "8.1.33"
  - "8.2.29"
  - "8.3.28"
  - "8.4.15"
image:
  composer:
    version: "2.9.2"
  php_extensions:
    redis:
      version: "6.3.0"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
