# The YAML configuration file for generating Dockerfile of image phpswoole/swoole.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
image:
  composer:
    version: "2.0.8"
  inotify: true
