# The YAML configuration file for generating Dockerfile of image phpswoole/swoole.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "8.0"
  - "8.1"
  - "8.2"
image:
  composer:
    version: "2.5.2"
  inotify: true
  php_extensions:
    redis:
      version: "5.3.7"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
