name: Build Latest Dev Images

on:
  schedule:
    - cron: '47 4 * * *'
  workflow_dispatch:

jobs:
  build_latest_images:
    runs-on: ubuntu-latest
    if: github.repository == 'swoole/docker-swoole'
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set full names of the Docker image
        id: set_full_names
        run: echo "{full_names}={phpswoole/swoole:php${{ matrix.php }}-dev}" >> $GITHUB_OUTPUT

      -
        name: Build and push Docker image phpswoole/swoole:php${{ matrix.php }}-dev
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/latest/php${{ matrix.php }}/cli/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: ${{ steps.set_full_names.outputs.full_names }}
          build-args: DEV_MODE=true

      -
        name: Image digest of phpswoole/swoole:php${{ matrix.php }}-dev
        run: echo ${{ steps.docker_build.outputs.digest }}
